### ISSUE TITLE
Identical Courses disappear in curriculum

### ISSUE THREAD

**Issue by ArturoAmaya** [ArturoAmaya/ExploratoryCurricularAnalytics#19]
The sets data structure used for curriculum generation makes identical courses, like `HILD` or `HIUD` disappear from the curriculum. This leads to some curriculums being very small. Ex. HI25 has 5 courses, but the major asks for 11. `HIUD` repeats three times and so does `HILD`.

**Comment by SheepTester** [comment]
ohhh is that why the units are under 180, no wonder. I wonder if there's an unordered list in python

**Comment by ArturoAmaya** [comment]
There's a thing called `collections.Counter` that I've never used before. I'm going to check that out right now.

**Comment by ArturoAmaya** [comment]
Seems to me that we can just revert to a list. I've seen very few differences in degree plans stem from taking an elective in a different order (especially when they're all just called `ELECTIVE`. As far as I know Curricular Analytics doesn't care about differences in order as long as the courses are all there, but I could be wrong. I defer to your judgement, though.
