### ISSUE TITLE
HI25 still too short

### ISSUE THREAD

**Issue by ArturoAmaya** [ArturoAmaya/ExploratoryCurricularAnalytics#21]
I figure this happens elsewhere too, but this is the representative example I stumbled on. Currently I'm messing around with a list of planned courses for the curriculum and I'm still getting an undercount of courses. There are supposed to be 15 major courses for history (3 LD and 12 UD). My count tops out at 13.

I'm missing a `HILD` and an `HIUD` (that one is unclear which quarter at the moment). 
Currently investigating.

**Comment by ArturoAmaya** [comment]
I just found that for HI25 anytime a course is listed twice with the same name in the same quarter, like `GE` or `Elective` in the original CSV it only shows up once in the corresponding representation. Will now attempt to replicated it with another major to confirm what the problem is.

**Comment by ArturoAmaya** [comment]
Sorry, I thought I had just committed an egregious mistake counting from 1 to 15. 

The major plan for `TH` has 13 total courses instead of the expected 15. Precisely the missing `HIUD` courses are the ones in year 3 quarters 1 and 2 where there are two `HIUD` courses per quarter on the plan and only one per quarter in the `major_codes["HI25"].plans["TH"]`. 

Issue is also observable with GEs. Year 1 quarter 1 specifies 2 GE courses but the script only picks up 1.

**Comment by ArturoAmaya** [comment]
Will now attempt to replicate with 3 other majors to "confirm" a system issue and not a freak accident.

**Comment by ArturoAmaya** [comment]
Showed it happens exactly the same with:  GL25, HI25, HS25 for Marshall and HS25 for Warren (only ones tested so far). 
![Screenshot (326)](https://user-images.githubusercontent.com/47407486/173423328-74ed441f-de3c-41cc-8983-5574d520b90f.png)
This is Marshall HI25. The plan calls for 15 courses for the major but there are only 13. In the upper pane you'll see that quarter 1 only has 1 GE, whereas our sheets and csv call for two.

![Screenshot (327)](https://user-images.githubusercontent.com/47407486/173423333-a2364af5-88f4-47c3-9a12-4a853fa3436e.png)
This is Marshall HDS25. Each quarter has less classes than they're supposed to. Quarter 1 has only one LD Major Prep, as does quarter 2. Quarter 3 has one less GE than called for as does quarter 4. 

![Screenshot (329)](https://user-images.githubusercontent.com/47407486/173423337-71fa664b-d12a-4e77-9443-9352f9fc0e63.png)
Same issue with GL25. Three GEs in quarter 1 get condensed into 1, two GEs in quarter 2 get condensed into one, same in quarter 3, and an elective disappears in quarter 4.

![Screenshot (330)](https://user-images.githubusercontent.com/47407486/173423340-959ee27f-e4f8-4d89-868d-99f879c7bce6.png)
Same with HDS25 but in Warren. 2 'LD Major Prep's become one in quarters 1 and 2, and a GE disappears in quarter 3.

Will look into why that happens.

**Comment by SheepTester** [comment]
Duplicate courses might be being swallowed up by sets as you noticed in #19 

With that fixed it now has 15 courses

![image](https://user-images.githubusercontent.com/22133785/173434248-703ea0fe-77fe-44a3-b443-f4a8aa276ade.png)
