### ISSUE TITLE
CIP codes

### ISSUE THREAD

**Issue by ArturoAmaya** [ArturoAmaya/ExploratoryCurricularAnalytics#23]
The CIP code output doesn't add a period after the first two digits. Curricular Analytics doesn't seem to complain, so it's seems like its no big deal.

**Comment by SheepTester** [comment]
I think the period is just for readability, but since in the already uploaded files, CS26's CIP code has a period in it, I probably should add it for consistency

**Comment by ArturoAmaya** [comment]
I went ahead and added it, for the same reasons.
