### ISSUE TITLE
Improving prerequisites

### ISSUE THREAD

**Issue by SheepTester** [ArturoAmaya/ExploratoryCurricularAnalytics#25]
Currently, to get a course's prerequisites, it just looks through all the courses in the degree plan, and if they show up anywhere in the course's prerequisites from prereqs.csv, it adds its ID to the prerequisites column.

However, as it turns out, this is probably not the wisest idea.

![image](https://user-images.githubusercontent.com/22133785/173460402-d2e2de79-5fdf-4d8d-8c65-4170d3343366.png)
In this mess of arrows, MATH 20A-C all point to PHYS 2A. This is because any of them satisfy the math prerequisite for PHYS 2A, so they all get added to PHYS 2A's prerequisites column, when in fact only MATH 20A is used as the prereq.

Also, in the hypothetical case where PHYS 2A is taken in the quarter after MATH 20B, I think there should only be one arrow from either MATH 20A or 20B because it seems the number of arrows affects its complexity score. For the purposes of figuring out how catastrophic failing a class is, I think output.py should take the earliest course in the plan (MATH 20A).

**Comment by SheepTester** [comment]
I think for each list of possible courses, I'll take the first course in the plan that shows up in the list.

**Comment by ArturoAmaya** [comment]
Sounds good. I hadn't even noticed that happened, well spotted. We should make a point to confirm with the Arizona team that that we do want to the lower complexity score (seems intuitive, but they're the experts).
