### ISSUE TITLE
Department name

### ISSUE THREAD

**Issue by SheepTester** [ArturoAmaya/ExploratoryCurricularAnalytics#28]
Currently, upload.py uses the major name (column E, "Major Description," of isis_major_code_list.xlsx) after the major code for the curriculum name.

https://github.com/ArturoAmaya/ExploratoryCurricularAnalytics/blob/8bab5be8d8b2e4cc4a1bdc56eea5e8840dbb90f8/upload.py#L264

IMO, the major name is good enough and probably is better for distinguishing between different majors under the same department.

However, the uploading instructions say

> - - Enter the name in this format: major code-department e.g. BE25- Bioengineering

Currently, none of the data we have gives department names, but they do give abbreviations of the major departments, both in column J, "Department," of isis_major_code_list.xlsx, and column A, "Department," of academic_plans.csv. For example, for BE25, both spreadsheets have `BENG` as its department.

I think it's feasible to get department names from the course catalog: https://catalog.ucsd.edu/front/courses.html

**Comment by ArturoAmaya** [comment]
Ok cool. Look into that, but I agree that using just the major is more readable. We could look into just putting the curricula into different Child Organization on the Curricular Analytics website and leave the current naming system.

**Comment by ArturoAmaya** [comment]
You also might want to use https://blink.ucsd.edu/instructors/academic-info/majors/major-codes.html for pairing major codes to departments.

**Comment by SheepTester** [comment]
> You also might want to use https://blink.ucsd.edu/instructors/academic-info/majors/major-codes.html for pairing major codes to departments, it has straight pairs

OH I thought that was the same as the major codes spreadsheet so I ignored it. That'll be useful, thanks!

**Comment by SheepTester** [comment]
```js
console.log(`[
${[...document.querySelectorAll('.body')].map(td => {
const major = td.parentNode.children[2]?.textContent || td.parentNode.nextElementSibling.children[1]?.textContent
return `    { '${major.slice(0, 2)}': '${td.textContent}' },`
}).join('\n')}
]`)
```
produces
```py
[
    { 'AN': 'Anthropology' },
    { 'BE': 'Bioengineering' },
    { 'BI': 'Biology' },
    { 'CH': 'Chemistry and Biochemistry' },
    { 'CG': 'Cognitive Science' },
    { 'EN': 'Economics' },
    { 'EC': 'Electrical and Computer Engineering' },
    { 'HS': 'Human Developmental Sciences' },
    { 'IN': 'Individual Studies' },
    { 'IS': 'International Studies' },
    { 'LT': 'Literature' },
    { 'MA': 'Mathematics' },
    { 'PY': 'Physics' },
    { 'PS': 'Political Science' },
    { 'SI': 'Scripps Institution of Oceanography' },
    { 'SO': 'Sociology' },
    { 'SE': 'Structural Engineering' },
    { 'TH': 'Theatre and Dance' },
    { 'UN': 'Undeclared' },
    { 'VA': 'Visual Arts' },
]
```

**Comment by ArturoAmaya** [comment]
Doesn't that skip out on some of the departments? `Chemical Engineering`, `African American Studies` and `Chinese Studies` and Classical Studies` and a few others don't show up. I think the CS department doesn't show up either.

**Comment by ArturoAmaya** [comment]
Huh, that's so weird that some of the rows just aren't given the body class... oh well.

**Comment by SheepTester** [comment]
`UNAF` probably stands for Unaffiliated (it has a mix of majors under it, and not much else)

`CENG` and `NENG` are probably Chemical and Nanoengineering (the catalog groups them under [`NANO`](https://catalog.ucsd.edu/courses/NANO.html))

`SPH` might be the [School of Public Health](https://hwsph.ucsd.edu/)

In looking for `GMST` I found this https://registrar.ucsd.edu/ver2/dservices/thirdweek/FA16/REGBDM04.FA16.PDF which is pretty nice except it abbreviates the department names which makes me unhappy, but it does seem to suggest that GMST is "German Studies" which is in line with the other regional studies departments

**Comment by ArturoAmaya** [comment]
I can confirm `CENG` and `NENG` are Chemical Engineering and Nano Engineering respectively. It's interesting that the catalog lists them both under Nano Engineering. The plans tool and the blink website list them as separate entities.

**Comment by ArturoAmaya** [comment]
Totally tangential, but that's a really cool document you uncovered. I'd never seen full enrollment numbers broken down like that :0

**Comment by SheepTester** [comment]
> Yup `UNAF` is unaffiliated, or at least that's what the plans tool calls it. It should have `UN27`, `UNHA`, `UNPS` and `UNSS`.

Ah, forgot that they also have a list of departments. Conveniently, all their names and codes are there directly 👏

![image](https://user-images.githubusercontent.com/22133785/173693070-1a17f8be-804f-48c4-82a6-1c6ea3b5fe56.png)

**Comment by ArturoAmaya** [comment]
Riiiiiiight I completely spaced on that one too. That's super convenient.
