### ISSUE TITLE
SOCI 60 is a prereq of SOCI UD Methodology

### ISSUE THREAD

**Issue by ArturoAmaya** [ArturoAmaya/ExploratoryCurricularAnalytics#34]
## SO31

[Uploaded](https://curricularanalytics.org/curriculums/13919), [generated](https://curricularanalytics.org/curriculums/19605)

The uploaded version uses "SOCI 10-50," which IMO is more confusing than the generated version's "SOCI 10, 20, 30, 40, OR 50" because it suggests all of them need to be taken, when only one needs to be taken.

It seems that generally, the uploaded names are more abbreviated, which is good because the names in the generated version tend to be clipped off because they're too long:
![image](https://user-images.githubusercontent.com/22133785/173703936-ad35498f-4971-4825-832e-7e051a565805.png)
The uploaded version uses a single letter for "concentration," "methodology," or "elective."

Only the uploaded version has a prereq from SOCI 60 to "SOCI UD M." This is not obvious from the given data we have but I think it might be important considering that SOCI 60 is a [prereq for many upper div sociology courses](https://catalog.ucsd.edu/courses/SOC.html) ⚠️ 

### Revelle

The generated version has "(DEI APPROVED)" and "(see note)"

Uploaded: "FINE ARTS GE"; generated: "FINE ARTS"

Uploaded: "AHI/Elective"; generated: "AHI or ELECTIVE"

The uploaded version also has a prereq from HUM 2 to HUM 3, while the generated version doesn't. This is a result of #25 because HUM 1 is enough for HUM 3

_Originally posted by @SheepTester in https://github.com/ArturoAmaya/ExploratoryCurricularAnalytics/issues/30#issuecomment-1155802114_

**Comment by ArturoAmaya** [comment]
In order

- Agreed that 10-50 is more confusing, it also implies that a course like SOCI 11 exists (it doesn't) and that it would satisfy the requirement. 
- Shortening the names might be worth doing. I know that the web tool lets you write annotations into the courses, so we could write an abbreviated name and the full version in the annotation if we can figure out how to annotate from the .csv
- I checked at the [SOCI department website](https://catalog.ucsd.edu/curric/SOC-ug.html) and they say that SOCI 60 is specifically a pre-req for every UD Methods course, so we should definitely add that in as a pre-req for "SOCI UD Methodology". We can probably add it to the pre-reqs document and re-download that, so that all our info is consistent. 
- What do you think of removing the "see note"? We don't have any note for people to see 😵‍💫

**Comment by SheepTester** [comment]
> * What do you think of removing the "see note"? We don't have any note for people to see 😵‍💫 . As for the other small name differences, that's no big deal right now, methinks.

Yeah I can go through and see what parentheses and slashes there are (some we might want to keep if they instead list alternative courses)
