### ISSUE TITLE
## TH27 - Moved to keep #30 clean

### ISSUE THREAD

**Issue by ArturoAmaya** [ArturoAmaya/ExploratoryCurricularAnalytics#35]
## TH27

Name: [uploaded](https://curricularanalytics.org/curriculums/14017) uses "Theater," [generated](https://curricularanalytics.org/curriculums/19602) uses "Theatre" (which I think is more correct)

Complexity is 2 less in the generated version

Only uploaded has prerequisites from TDTR 10 -> TDDM 101 and TDHD XXX. Only generated has prerequisites from TDDM 1 to 101. The main difference here I think is that for TDDM 101's prerequisites, the uploaded version says it's TDTR 10 while the generated version says it's TDDM 1. According to the [course catalog](https://catalog.ucsd.edu/courses/THEA.html#tddm101), it's only TDDM 1.

![image](https://user-images.githubusercontent.com/22133785/173702498-d1cad19f-476c-4437-a3bc-c9e51517fa6e.png)

Another difference is that the uploaded version uses "UD Elective Mvmnt *n*," while the generated version calls them all "UD Elective Movement." Similarly for Core Movement. Maybe we might want to consider adding numbers to duplicate course names? (This is the case for degree plans too, eg "GE") ⚠️ 

### Revelle

The generated version has one more curr. compl. Core movements have been moved from terms 9 and 10 in the uploaded version to terms 2 and 4 in the generated version (This is the case for many other degree plans)

The uploaded version calls it "CHEM GE" while the generated version calls it "CHEMISTRY GE (see note)"

### Muir

Uploaded: "MCWP 40"; generated: "MCWP 40/GE"

### Marshall

Uploaded: "DOC 1"; generated: "DOC 1/DEI"

### Warren

Interestingly, uploaded: "PHIL/POLI 1"; generated: "PHIL/POLI 27." I think 1/2 here means "PHIL/POLI" is just a generic elective sequence, while the generated version has specific course

### Sixth

Uploaded: "CAT 125"; generated: "PRACTICUM OR CAT 125"

_Originally posted by @SheepTester in https://github.com/ArturoAmaya/ExploratoryCurricularAnalytics/issues/30#issuecomment-1155791620_

**Comment by ArturoAmaya** [comment]
About numbering the electives, I think that's a fairly good idea. Would courses like `MCWP40/GE` factor into the the numbering?

**Comment by SheepTester** [comment]
I think we'd probably just chop off the /GE /DEI /AWP stuff like you mentioned in "Issues"
