### ISSUE TITLE
## PY29 - Moved to keep #30 clean

### ISSUE THREAD

**Issue by ArturoAmaya** [ArturoAmaya/ExploratoryCurricularAnalytics#36]
## PY29

[Uploaded](https://curricularanalytics.org/curriculums/13981), [generated](https://curricularanalytics.org/curriculums/19608)

The prerequisites do be looking quite dense
![image](https://user-images.githubusercontent.com/22133785/173705432-99ae685e-d59c-453a-b6b8-b691534ac0f6.png)

Interestingly, the uploaded version lists math 20a as what seems to be a corequisite of math 18, while the generated version says math 20a is a prerequisite. The generated version isn't wrong because math 20a satisfies math 18's prerequisites. However, in practice, because we assume students have satisfied pre-calc, which is also an alternative prereq of math 18, students should be able to take 20a and 18 in the same quarter. This ultimately puts math 18 in a later column in the curriculum, but shouldn't affect degree plans I think. ⚠️ 

The uploaded version lists phys 4e as a prereq for phys 110a (in addition to math 20e), which makes it one column longer than the generated version. The generated version instead has phys 4d.

Interestingly, PHYS 4E isn't even a prereq for PHYS 110A:
![image](https://user-images.githubusercontent.com/22133785/173706410-a74bc386-5c9d-4bc2-8833-fb91cbb6036e.png)
so the uploaded version appears to be wrong.

Only the uploaded version lists math 20e as a prereq for phys 105a, but the generated version doesn't. I'm not sure why. I'll have to look into this. 🚩 

Only the uploaded version lists math20e as a prereq for phys 100a. The generated version doesn't because math 20d already does

Only the generated version lists phys 4e as a prereq for phys 130a. I don't know why the uploaded version doesn't, but this might have to do with it listing phys 110a, another prereq of 130a, as requiring phys 4e.

Only the generated version lists math 20e as a prereq for phys 4d. This is correct.

### Revelle

![image](https://user-images.githubusercontent.com/22133785/173707176-c28907b4-eae1-487b-b97f-b1885efc020f.png)

that's a lot of lines

For some reason, PHYS 2DL is in term 6 in the uploaded version but term 7 in the generated version.

More significantly, the updated version uses a corequisite arrow from math 20a to math 18 while the generated version uses a prerequisite arrow, despite the two courses being in the same quarter. Curricular Analytics renders this fine, but I think this should be changed: 🚩 

1. When editing the degree plan directly (by enabling editing mode, which I used to reorder the courses within quarters), math 18 pops ahead of 20a and can't be placed in the same quarter. This leads to somewhat buggy but not catastrophic behavior when you try to drag math 20a because it shows up to the left of the entire plan off the screen. Fortunately it snaps back to term 1 when you let go.
![image](https://user-images.githubusercontent.com/22133785/173709402-fc36953c-0eea-4bb9-a85c-c71e6b5f5f78.png)

2. It probably also affects the complexity score (since it might think that math 20a blocks more courses than it actually should normally)

Since I don't think math 18 and 20a are listed as prereqs with concurrent enrollment enabled (I'd have to check this), to fix this, I could check if a prerequisite is in the same or later quarter and mark it as a corequisite instead

_Originally posted by @SheepTester in https://github.com/ArturoAmaya/ExploratoryCurricularAnalytics/issues/30#issuecomment-1155825734_

**Comment by ArturoAmaya** [comment]
> Only the uploaded version lists math 20e as a prereq for phys 105a, but the generated version doesn't. I'm not sure why. I'll have to look into this. 🚩

Hmmm, that's really strange. It shows up in the .csv, so maybe Curricular Analytics is doing something to it?

**Comment by ArturoAmaya** [comment]
> Only the uploaded version lists math 20e as a prereq for phys 105a, but the generated version doesn't. I'm not sure why. I'll have to look into this. 🚩

This happens because the generated version lists 4D as a pre-req of 105a when the uploaded version does not. Then, the generated version lists 20E as a pre-req for both 4D and 4E when the uploaded version does not. When the GUI is generated from the generated version, 20E folds into 4D and 4E pre-reqs and we get that only 4E is a direct pre-req of 105a. In the uploaded version, since 105a doesn't depend on 4D and neither 4D nor 4E depend on 20E but 105 depends on 20E, 20E is at the top of a pre-req chain for 105a and thus appears as a direct pre-req. 

Per the catalog:
![image](https://user-images.githubusercontent.com/47407486/173955851-3481a5a7-583c-44ba-820f-f529c673e837.png)
4D indeed depends on 20E, as does 4E.
![image](https://user-images.githubusercontent.com/47407486/173955982-d140fc19-175b-493d-a45e-b222c293cc85.png)
105a does indeed depend on 4D. 

That is, the generated version is correct. Interestingly, the generated version lists 4B as a requirement when only 4C-D-E are required. 
![image](https://user-images.githubusercontent.com/47407486/173956333-86560c54-bc08-4594-89df-d0548a85bd92.png)
This is inherited from the pre-reqs document. I will flag it.
![image](https://user-images.githubusercontent.com/47407486/173956614-9907e058-8d1d-4c33-8a2c-b067a96eb3a3.png)

**Comment by ArturoAmaya** [comment]
> Only the generated version lists phys 4e as a prereq for phys 130a. I don't know why the uploaded version doesn't, but this might have to do with it listing phys 110a, another prereq of 130a, as requiring phys 4e.

Yeah, that's roughly it. The catalog explicitly lists 100A, 110A and 4E as pre-reqs for 130A. The .csv for the uploaded version lists all three, but it also lists 4E as a direct pre-req of 100A and 110A. The catalog disagrees - 4E is not a pre-req of 100A or 110A.

So, in the uploaded version 4E folds into being a direct pre-req of 100A and 110A, which are in turn direct pre-reqs of 130A. That is incorrect. The correct form is the generated form, where 4E is not a prereq of either, so it is a direct pre-req of 130A.

**Comment by ArturoAmaya** [comment]
> For some reason, PHYS 2DL is in term 6 in the uploaded version but term 7 in the generated version.

Yeah, no idea but it matches with the online plan generator, so it's totally fine.

**Comment by SheepTester** [comment]
Seems like the generated version is correct so I'll close this
