### ISSUE TITLE
Math 18 prerequisite

### ISSUE THREAD

**Issue by SheepTester** [ArturoAmaya/ExploratoryCurricularAnalytics#37]
Discovered in #30 

Because we assume everyone already has pre-calc credit, math 18 doesn't have any actual prerequisites. However, prereqs.csv does (correctly) list math 20a as a possible prerequisite for math 18, so if they show up in the same quarter, the generator will wrongly say that math 20a is a prereq for math 18.

I think the best course of action here is to add code that just ignores any prerequisites for math 18:

- It's very easy
- Saying that math 18 has any prerequisites is misleading, even if math 20a is taken before math 18, because saying math 18 requires math 20a makes it seem like failing math 20a is more catastrophic than it actually is (i.e. it affects the complexity score)

We might also want to add a check for any prerequisites that show up in a quarter in or after a course

**Comment by ArturoAmaya** [comment]
Yup! I agree that removing prereqs from `MATH 18` makes sense. I just think it would be easier if we edit the prereqs doc we have. In the meantime, I'll flag it, but I won't delete it just yet.
