### ISSUE TITLE
Degree plan course IDs need to match those in their curriculum

### ISSUE THREAD

**Issue by SheepTester** [ArturoAmaya/ExploratoryCurricularAnalytics#39]
Discovered in #30 

So apparently Curricular Analytics is very annoying, and for determining prerequisites of a course, it uses the course IDs from the curriculum.

We had I guess unwisely assumed that degree plans are completely independent, but they aren't. We've gone so long without noticing because major courses *tend* (with some exceptions) to be taken in the same order per major, so they get assigned the same course IDs. However, we can't rely on this

Fortunately, this is only relevant for prerequisites; courses that do not have prerequisites or are not prerequisites do not need to have a stable course ID. This is particularly relevant for some courses that can't be prerequisites because no meaningful course name can be parsed from them (eg "ELECTIVE")

I think the way I'll approach this is to get the curriculum (based on Marshall's academic plan) first, give IDs to each course (whose name can be parsed, i.e. a specific course subject + number rather than a generic "CSE elective"), and then use these IDs for degree plans.

Some investigation might be required to see if Curricular Analytics requires course IDs to be sorted, consecutive, etc. (i.e. whether I can just make them jump around), but I think I'll just assume it's nice and they just care they're unique and hope it's not more complicated than that <img src="https://cdn.discordapp.com/emojis/970867866926710794.webp?size=128&quality=lossless" height="16">

**Comment by ArturoAmaya** [comment]
Sounds good boss. This morning I totally missed this and just sorted the courses alphabetically when they were parsed into degree plans (importantly, pre-curriculum) and it seems to have made most of the stuff go away, but I'm not quite sure. I commented on #30 if you want to check it out. Feel free to do either, and figuring out whether or not CA requires course IDs to be sorted is pretty interesting.

**Comment by SheepTester** [comment]
It seems CA doesn't really care if the IDs are sorted

Sorting the course names should help, but are there any degree plans where a major course is taken in a different quarter? Because I think that might still change its course ID

**Comment by ArturoAmaya** [comment]
Off the top of my head I can't remember, but I'll investigate that now.

**Comment by ArturoAmaya** [comment]
I'm taking this for a spin with MC25 and MC27 (the two most complicated majors I know). So far so good with MC25! 👍
