### ISSUE TITLE
BE28/Sixth has a keyError

### ISSUE THREAD

**Issue by ArturoAmaya** [ArturoAmaya/ExploratoryCurricularAnalytics#47]
![image](https://user-images.githubusercontent.com/47407486/174863810-b6ebef2f-ea5b-428d-a582-21ef5f73c8f1.png)
Not quite sure why this is happening... I'm going to check it out

**Comment by ArturoAmaya** [comment]
yup, specifically BENG 168 in term 11 is a requisite for BENG 187A in term 9. Makes no sense to take the requisite half a year later

**Comment by ArturoAmaya** [comment]
Yknow, the funny thing is... That's what's on the degree plan. I'm going to check the catalog

**Comment by SheepTester** [comment]
![image](https://user-images.githubusercontent.com/22133785/174868816-729e24ad-0d80-41da-adbb-e6df50882930.png)

It seems that normal bioengineering (BE25) does have a BENG 112A before 187A,
![image](https://user-images.githubusercontent.com/22133785/174868911-bc0da945-2ece-45ee-97ca-2f67d8b9ce59.png)

but maybe the advisors just forgot about that for bioinformatic majors

**Comment by ArturoAmaya** [comment]
> I guess we could just suppress the error by not listing a prerequisite if they're in a future quarter

I guess for now that works, but I want to find out why that is on the degree plan in the first place...

**Comment by ArturoAmaya** [comment]
Ok kewl... I'll keep you posted on what the advising people say - they might just up and change it so we wouldn't need to do too much.
