### ISSUE TITLE
Unfinished Equality Check for curriculums extracted from degree plans

### ISSUE THREAD

**Issue by ArturoAmaya** [ArturoAmaya/ExploratoryCurricularAnalytics#9]
Work for tomorrow:

- [ ] Check that quarters with the same courses in a different order are the same (currently they register as different)
- [ ] Check that quarters with the same courses that differ by a overlaps_with_GE (currently they register as different)
- [ ] Comments for the large script

**Comment by ArturoAmaya** [comment]
Done on arturo_messing_around, which is no longer aptly named

**Comment by SheepTester** [comment]
Hmm, we could change the list of courses to a set because they're unordered. Could also override the `__eq__` method to make it ignore `overlaps_with_ge`

```py
>>> set([1, 2]) == set([2, 1])
True
```
